### ISSUE TITLE
Post launch checklist

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#417]
- [ ] recheck testing list
- [ ] Check load time for site pages is optimised
- [ ] Check analytics
- [ ] Monitor Search Console

**Comment by ncktrnr** [comment]
Suggest we close this one and create new issues as required. For example a full review of Google Search Console would be a worthwhile task.
