### ISSUE TITLE
Cross site fixes

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#496]
- [x] Fix content by collection view - cards not showing properly  + new description field 
- [x] Staff to projects, make this work properly
- [x] Fix press pagination, quirk with layout builder
- [x] Project pagination 
- [x] Update tags filter to exclude tag type 3|Location 
- [x] Update how project contacts display
- [x] Blog cc link needs mb-4
- [x] Blog check paragraph quotes have cite option 
- [x] https://iied.org/admin/popular-tags Add views to twig with container 
- [x] Replacement cover image too large, check twig
- [x] cite link not [iied.org](http://iied.org/) update view. 
- [x] minor update to pubs twig to remove flex from author div and remove extra ; 
- [x] Eds not displaying properly https://iied.org/21111iied
- [x] Add field twig for related links paragraph on person 
- [x] News insight view News insight featured (Content) change view filter
- [x] Fix: pubs load more feature on project pages#473
- [x] Contact page duplicated#474
- [x] Fix: news and insight page missing content between views#475
- [x] Admin UI - Adding new Authors#471 
- [x] Add reporting view for Q stats
